name: Build Dolphin Emulator

on:
  push:
    paths:
      - '.github/workflows/build-dolphin.yml'
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash of the Dolphin repository'
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc g++ git libwxgtk3.0-gtk3-dev libgtk-3-dev libasound2-dev libpulse-dev libudev-dev libevdev-dev libxi-dev libxrandr-dev libopenal-dev libmbedtls-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libusb-1.0-0-dev libsfml-dev qtbase5-dev

      - name: Clone Dolphin Emulator
        run: |
          git clone https://github.com/dolphin-emu/dolphin.git
          cd dolphin
          if [ "${{ github.event.inputs.commit_hash }}" != "latest" ]; then
            git checkout ${{ github.event.inputs.commit_hash }}
          fi
          git submodule update --init --recursive
          
      - name: Build Dolphin Emulator
        run: |
          cd dolphin
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Archive Build
        run: |
          cd dolphin/build
          tar -czvf dolphin-emu.tar.gz *

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dolphin-emu
          path: dolphin/build/dolphin-emu.tar.gz

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dolphin/build/dolphin-emu.tar.gz
          asset_name: dolphin-emu.tar.gz
          asset_content_type: application/gzip
